### PR TITLE
Angular 9 update, Fixes to RRule processing for end component

### PR DESCRIPTION
**Pull request by zainniazi**
- Moving to Angular 9
- Switching BroswerModule to CommonModule to solve the LazyLoad Module import problem.
- Fixes to RRule processing for end component
This PR fixes the problems on end component which occur with until date due to incorrect format of date object.
Until Issue

### CODE REVIEW

**Comment by zainniazi** [comment]
Hi @kumar-muthu,
Can you please look at this ?

Thanks

**Comment by kumar-muthu** [comment]
> Hi @kumar-muthu,
> Can you please look at this ?
> 
> Thanks

I'll check and push a new version in a couple of days.

**Comment by kumar-muthu** [comment]
@zainniazi I see a lot of changes apart from the BroswerModule. Please add details of the changes in this pull request.

**Comment by zainniazi** [comment]
@kumar-muthu i discovered few more issues and included them in this PR,
Please have a look at the description.

**Comment by kumar-muthu** [comment]
@zainniazi I have accepted your commits and have made some changes on top of it. Closing this.

**Pull request closed without merging**
